EjercicioTecnico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from Usuario.views import Login
from Usuario.views import Logout
from Usuario.views import RegistarUsuario
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Usuario.views import Listar_foto,AdicionaFoto, ModificaFoto, VisualizaFoto, BorraFoto

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Login.as_view(), name='login'),
    url(r'^registro/', RegistarUsuario.as_view(), name='registro'),
    url(r'^listar_foto/', Listar_foto.as_view(), name='listar_foto'),
    url(r'^adicionar_foto/', AdicionaFoto.as_view(), name='adicionar_foto'),
    url(r'^modificar_foto/(?P<id_foto>\w+)', ModificaFoto.as_view(), name='modificar_foto'),
    url(r'^visualizar_foto/(?P<id_foto>\w+)', VisualizaFoto.as_view(), name='visualizar_foto'),
    url(r'^borrar_foto/(?P<id_foto>\w+)', BorraFoto.as_view(), name='borrar_foto'),
    url(r'logout/', Logout.as_view(), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuario/models.py
from django.db import models
from django.db.models.fields import AutoField, CharField, EmailField

# Create your models here.
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

DOC_CHOICESUSU = (
    ('AD', _(u"Administrador")),
    ('CLI', _(u"Cliente")),
)

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    rol = models.CharField(max_length=10, choices= DOC_CHOICESUSU, default='CLI')
    usuid = models.OneToOneField(User, on_delete=models.CASCADE)


class Foto(models.Model):
    id_foto = models.AutoField(primary_key=True)
    imagen = models.ImageField(upload_to='fotos')

Usuario/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from Usuario.models import Foto



DOC_CHOICESUSU = (
    ('AD', _(u"Administrador")),
    ('CLI', _(u"Cliente")),
)

class FotoForm(forms.ModelForm):
    class Meta:
        model = Foto
        fields = "__all__"
        labels = {
            'foto': _(u'foto'),
        }

    def __init__(self, *args, **kwargs):
        super(FotoForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class Registroform(forms.Form):
    username = forms.CharField(max_length=150, label='Username')
    email = forms.EmailField(max_length=150, label='Email')
    password = forms.CharField(max_length=128, label='Contraseña', widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=128, label='Confirmar Contraseña', widget=forms.PasswordInput())

    nombres = forms.CharField(max_length=50, label='Nombres')
    apellidos = forms.CharField(max_length=50, label='Apellidos')
    rol = forms.ChoiceField(choices=DOC_CHOICESUSU, label="Tipo de Usuario", widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super(Registroform, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

templates/adicionar_cliente.html
{% extends 'base_crud_cliente.html' %}

{% block titulo_formulario_cliente %}
    <i class="fa fa-plus-square page-header-icon"></i>&nbsp;Registrar Usuario
{% endblock %}

{% block boton_accion_cliente %}
    <button type="submit" class="btn btn-primary">Adicionar</button>
{% endblock %}

templates/agregar_foto.html
{% extends 'base_crud.html' %}

{% block titulo_formulario_vehiculo %}
    <i class="fa fa-plus-square page-header-icon"></i>&nbsp;Registrar Foto
{% endblock %}

{% block boton_accion_vehiculo %}
    <button type="submit" class="btn btn-primary">Adicionar</button>
{% endblock %}

templates/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
    <!--[if IE 8]>         <html class="ie8"> <![endif]-->
    <!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
    <!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Ejercicio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <!-- Pixel Admin's stylesheets -->
        <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/widgets.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/themes.min.css' %}" rel="stylesheet" type="text/css">

        {% block styles %}
        {% endblock %}

        <!--[if lt IE 9]>
            <script src="{% static 'javascripts/ie.min.js' %}"></script>
        <![endif]-->
    </head>

    <body class="theme-frost main-menu-animated">
        <div id="main-wrapper">
            <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
                <!-- Main menu toggle -->
                <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

                <div class="navbar-inner">
                    <!-- Main navbar header -->
                    <div class="navbar-header">

                        <!-- Logo -->
                        <a href="{% url 'logout' %}" class="navbar-brand">Ejercicio
                        </a>

                        <!-- Main navbar toggle -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

                    </div> <!-- / .navbar-header -->

                    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                        <div>
                            <div class="right clearfix" style="background-color: #2a2d33">
                                <ul class="nav navbar-nav pull-right right-navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown" style="color: white;">
                                            <span>{{ user.first_name }}&nbsp;{{ user.last_name }}</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="">
                                                    <i class="dropdown-icon fa fa-user"></i>&nbsp;&nbsp;Perfil
                                                </a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{% url 'logout' %}">
                                                    <i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Cerrar Sesión
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul> <!-- / .navbar-nav -->
                            </div> <!-- / .right -->
                        </div>
                    </div> <!-- / #main-navbar-collapse -->
                </div> <!-- / .navbar-inner -->
            </div> <!-- / #main-navbar -->
        <!-- /2. $END_MAIN_NAVIGATION -->
            <div id="main-menu" role="navigation">
                <div id="main-menu-inner">
                    <div class="menu-content top" id="menu-content-demo">
                        <div>
                            <div class="text-bg">
                                <span class="text-slim">Bienvenido,</span><br>
                                <span class="text-semibold">{{ user.first_name }}</span>
                            </div>
                            {% comment %}<img src="{{ foto_usuario.url }}" id="img_usuario" alt="Foto Usuario">{% endcomment %}
                            <a href="#" class="close">&times;</a>
                        </div>
                    </div>
                    <ul class="navigation">
                        <li id="item_usuario">
                            <a href="{% url 'listar_foto' %}">
                                <i class="menu-icon fa fa-user"></i>
                                <span class="mm-text">Fotos</span>
                            </a>
                        </li>
                        <li>

                            <a href="{% url 'logout' %}">
                                <i class="menu-icon fa fa-power-off"></i>
                                <span class="mm-text">Cerrar Sesion</span>
                            </a>
                        </li>
                    </ul> <!-- / .navigation -->
                </div> <!-- / #main-menu-inner -->
            </div> <!-- / #main-menu -->
        <!-- /4. $MAIN_MENU -->
            <div id="content-wrapper">

                {% block content %}
                {% endblock %}

            </div> <!-- / #content-wrapper -->
            <div id="main-menu-bg"></div>
        </div> <!-- / #main-wrapper -->
        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->
        <!-- Pixel Admin's javascripts -->
        <script src="{% static 'javascripts/bootstrap.min.js' %}"></script>
        <script src="{% static 'javascripts/pixel-admin.min.js' %}"></script>
        <script>var init = [];</script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
        {% block scripts %}
        {% endblock %}

    </body>
</html>

templates/base_crud.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Administrar Fotos
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            {% block titulo_formulario_vehiculo %}
            {% endblock %}
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col" >
            <div class="profile-block">
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel" style="border-radius: 60px; width: 820px; margin-top: -0px; margin-left: 220px">
                    <br><br>
                    <form method="post" id="form_cliente" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% include 'form_cliente.html' %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                {% block boton_accion_vehiculo %}
                                {% endblock %}
                                <a href="{% url 'listar_foto' %}">
                                    <button type="button" class="btn btn-danger">Salir</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_vehiculos').addClass("active");
            $('#id_vehfoto').pixelFileInput({ placeholder: 'Seleccione una imagen para el usuario'});
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

templates/base_crud_cliente.html
{% extends 'base_usurios.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'alerts.html' %}
    <div class="profile-full-name">
        <span class="text-semibold">
            {% block titulo_formulario_cliente %}
            {% endblock %}
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_cliente" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% include 'form_cliente.html' %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                {% block boton_accion_cliente %}
                                {% endblock %}
                                <a href="{% url 'login' %}">
                                    <button type="button" class="btn btn-danger">Salir</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

templates/base_usurios.html
{% load static %}

<!DOCTYPE html>
    <!--[if IE 8]>         <html class="ie8"> <![endif]-->
    <!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
    <!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Registro</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <!-- Pixel Admin's stylesheets -->
        <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/widgets.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/themes.min.css' %}" rel="stylesheet" type="text/css">

        {% block styles %}
        {% endblock %}

        <!--[if lt IE 9]>
            <script src="{% static 'javascripts/ie.min.js' %}"></script>
        <![endif]-->
    </head>

    <body class="theme-frost main-menu-animated">
        
        <!-- /4. $MAIN_MENU -->
            <div id="content-wrapper">

                {% block content %}
                {% endblock %}

            </div> <!-- / #content-wrapper -->
        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->
        <!-- Pixel Admin's javascripts -->
        <script src="{% static 'javascripts/bootstrap.min.js' %}"></script>
        <script src="{% static 'javascripts/pixel-admin.min.js' %}"></script>
        <script>var init = [];</script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
        {% block scripts %}
        {% endblock %}

    </body>
</html>

templates/eliminar_foto.html
{% extends 'base_crud.html' %}

{% block titulo_formulario_vehiculo %}
    <div class="cliente" style="margin-left: 230px; font-size: 22px">
        <i class="fa fa-eraser page-header-icon"></i>&nbsp;Borrar Foto
    </div>
{% endblock %}

{% block boton_accion_vehiculo %}
    <button type="submit" class="btn btn-primary">Borrar</button>
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_vehiculo').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_vehiculo').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>
{% endblock %}

templates/form_cliente.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="jq-validation-url" class="col-sm-3 control-label">
            <strong>{{ field.label }}</strong>
        </label>
        <div class="col-sm-9">
            {{ field }}
        </div>
    </div>
{% endfor %}

templates/listar_fotos.html
{% extends 'base.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>&nbsp;&nbsp;Administración de Fotos
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- "Create project" button, width=auto on desktops -->
                    <div class="pull-right col-xs-12 col-sm-auto">
                        <a href="{% url 'adicionar_foto'%}" class="btn  btn-labeled btn-primary">
                               <span class="btn-label icon fa fa-plus"></span>
                                    Adicionar Foto
                        </a>
                    </div>
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>imagen</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for foto in fotos %}
                        <tr class="odd gradeX">
                            <td>{{ forloop.counter }}</td>
                            <td><img src="{{foto.imagen.url}}" style="height: 100px; width: 100px; border-radius: 50px 50px 50px 50px;" ></td>
                            
                            <td>
                                <div class="btn-group" >
                                    <a href="{% url 'visualizar_foto' foto.id_foto %}" class="btn btn-primary">Visualizar</a>
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-caret-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" style="z-index: 100 !important;">
                                        <li><a href="{% url 'modificar_foto' foto.id_foto %}" >Modificar</a></li>
                                        <li><a href="{% url 'borrar_foto' foto.id_foto %}">Eliminar</a></li>
                                    </ul>
                                </div>&nbsp;
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Listado de Clientes');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });
    </script>
{% endblock %}

templates/modificar_foto.html
{% extends 'base_crud.html' %}

{% block titulo_formulario_vehiculo %}
    <i class="fa fa-edit page-header-icon"></i>Modificar Foto
{% endblock %}

{% block boton_accion_vehiculo %}
    <button type="submit" class="btn btn-primary">Modificar</button>
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#id_rol').prop('readonly', true);
        $('#id_rol').prop('disabled', true);
        $('#id_usuid').prop('readonly', true);
        $('#id_usuid').prop('disabled', true);

    </script>
{% endblock %}

templates/pages-404.html
{% load static %}

<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Error 404 - Pages - PixelAdmin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

	<!-- Open Sans font from Google CDN -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">

	<!-- Pixel Admin's stylesheets -->
    <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">

	<!--[if lt IE 9]>
        <script src="{% static 'javascripts/ie.min.js' %}"></script>
    <![endif]-->

</head>


<!-- 1. $BODY ======================================================================================

	Body

	Classes:
	* 'right-to-left' - Sets text direction to right-to-left
-->
<body class="page-404">

<script>var init = [];</script>

	<div class="header">
		<a href="{% url 'login' %}" class="logo">
			<div>
                <img src="{% static 'images/pixel-admin/main-navbar-logo.png' %}">
            </div>&nbsp;
		</a> <!-- / .logo -->
	</div> <!-- / .header -->

	<div class="error-code">404</div>

	<div class="error-text">
		<span class="oops">OOPS!</span><br>
		<span class="hr"></span>
		<br>
		{{ msg }}
	</div> <!-- / .error-text -->

</body>
</html>

templates/visualizar_foto.html
{% extends 'base_crud.html' %}

{% block titulo_formulario_vehiculo %}
    <divclass="cliente" style="margin-left: 230px; font-size: 22px">
         <i class="fa fa-eye page-header-icon"></i>&nbsp;Visualizar Foto
    </div>
{% endblock %}

{% block boton_accion_vehiculo %}
{% endblock %}

{% block scripts_crud %}
    <script>
        $('#form_vehiculo').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_vehiculo').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>
{% endblock %}